// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRM.Interface.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of rra_program
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.rra_programCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMrraProgramCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrraProgramCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMrraProgramCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrraProgramCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMrraProgramCollection(IList<MicrosoftDynamicsCRMrraProgram> value = default(IList<MicrosoftDynamicsCRMrraProgram>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMrraProgram> Value { get; set; }

    }
}
