// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRM.Interface.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.systemuserauthorizationchangetracker
    /// </summary>
    public partial class MicrosoftDynamicsCRMsystemuserauthorizationchangetracker
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMsystemuserauthorizationchangetracker class.
        /// </summary>
        public MicrosoftDynamicsCRMsystemuserauthorizationchangetracker()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMsystemuserauthorizationchangetracker class.
        /// </summary>
        public MicrosoftDynamicsCRMsystemuserauthorizationchangetracker(long? computedversionnumber = default(long?), System.DateTimeOffset? changedon = default(System.DateTimeOffset?), long? changedversionnumber = default(long?), string systemuserid = default(string), System.DateTimeOffset? computedon = default(System.DateTimeOffset?), IList<MicrosoftDynamicsCRMsyncerror> systemuserauthorizationchangetrackerSyncErrors = default(IList<MicrosoftDynamicsCRMsyncerror>), IList<MicrosoftDynamicsCRMasyncoperation> systemuserauthorizationchangetrackerAsyncOperations = default(IList<MicrosoftDynamicsCRMasyncoperation>), IList<MicrosoftDynamicsCRMmailboxtrackingfolder> systemuserauthorizationchangetrackerMailboxTrackingFolders = default(IList<MicrosoftDynamicsCRMmailboxtrackingfolder>), IList<MicrosoftDynamicsCRMprocesssession> systemuserauthorizationchangetrackerProcessSession = default(IList<MicrosoftDynamicsCRMprocesssession>), IList<MicrosoftDynamicsCRMbulkdeletefailure> systemuserauthorizationchangetrackerBulkDeleteFailures = default(IList<MicrosoftDynamicsCRMbulkdeletefailure>), IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> systemuserauthorizationchangetrackerPrincipalObjectAttributeAccesses = default(IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess>), MicrosoftDynamicsCRMsystemuser systemuseridUserauthztracker = default(MicrosoftDynamicsCRMsystemuser))
        {
            Computedversionnumber = computedversionnumber;
            Changedon = changedon;
            Changedversionnumber = changedversionnumber;
            Systemuserid = systemuserid;
            Computedon = computedon;
            SystemuserauthorizationchangetrackerSyncErrors = systemuserauthorizationchangetrackerSyncErrors;
            SystemuserauthorizationchangetrackerAsyncOperations = systemuserauthorizationchangetrackerAsyncOperations;
            SystemuserauthorizationchangetrackerMailboxTrackingFolders = systemuserauthorizationchangetrackerMailboxTrackingFolders;
            SystemuserauthorizationchangetrackerProcessSession = systemuserauthorizationchangetrackerProcessSession;
            SystemuserauthorizationchangetrackerBulkDeleteFailures = systemuserauthorizationchangetrackerBulkDeleteFailures;
            SystemuserauthorizationchangetrackerPrincipalObjectAttributeAccesses = systemuserauthorizationchangetrackerPrincipalObjectAttributeAccesses;
            SystemuseridUserauthztracker = systemuseridUserauthztracker;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "computedversionnumber")]
        public long? Computedversionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "changedon")]
        public System.DateTimeOffset? Changedon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "changedversionnumber")]
        public long? Changedversionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserid")]
        public string Systemuserid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "computedon")]
        public System.DateTimeOffset? Computedon { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_SyncErrors")]
        public IList<MicrosoftDynamicsCRMsyncerror> SystemuserauthorizationchangetrackerSyncErrors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_AsyncOperations")]
        public IList<MicrosoftDynamicsCRMasyncoperation> SystemuserauthorizationchangetrackerAsyncOperations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_MailboxTrackingFolders")]
        public IList<MicrosoftDynamicsCRMmailboxtrackingfolder> SystemuserauthorizationchangetrackerMailboxTrackingFolders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_ProcessSession")]
        public IList<MicrosoftDynamicsCRMprocesssession> SystemuserauthorizationchangetrackerProcessSession { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_BulkDeleteFailures")]
        public IList<MicrosoftDynamicsCRMbulkdeletefailure> SystemuserauthorizationchangetrackerBulkDeleteFailures { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserauthorizationchangetracker_PrincipalObjectAttributeAccesses")]
        public IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> SystemuserauthorizationchangetrackerPrincipalObjectAttributeAccesses { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "systemuserid_userauthztracker")]
        public MicrosoftDynamicsCRMsystemuser SystemuseridUserauthztracker { get; set; }

    }
}
