// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRM.Interface.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Microsoft.Dynamics.CRM.indexattributes
    /// </summary>
    public partial class MicrosoftDynamicsCRMindexattributes
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMindexattributes class.
        /// </summary>
        public MicrosoftDynamicsCRMindexattributes()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMindexattributes class.
        /// </summary>
        public MicrosoftDynamicsCRMindexattributes(long? recordid = default(long?), string versionnumber = default(string), string indexid = default(string), string indexattributeid = default(string), IList<MicrosoftDynamicsCRMsyncerror> indexattributesSyncErrors = default(IList<MicrosoftDynamicsCRMsyncerror>), IList<MicrosoftDynamicsCRMasyncoperation> indexattributesAsyncOperations = default(IList<MicrosoftDynamicsCRMasyncoperation>), IList<MicrosoftDynamicsCRMmailboxtrackingfolder> indexattributesMailboxTrackingFolders = default(IList<MicrosoftDynamicsCRMmailboxtrackingfolder>), IList<MicrosoftDynamicsCRMbulkdeletefailure> indexattributesBulkDeleteFailures = default(IList<MicrosoftDynamicsCRMbulkdeletefailure>), IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> indexattributesPrincipalObjectAttributeAccesses = default(IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess>))
        {
            Recordid = recordid;
            Versionnumber = versionnumber;
            Indexid = indexid;
            Indexattributeid = indexattributeid;
            IndexattributesSyncErrors = indexattributesSyncErrors;
            IndexattributesAsyncOperations = indexattributesAsyncOperations;
            IndexattributesMailboxTrackingFolders = indexattributesMailboxTrackingFolders;
            IndexattributesBulkDeleteFailures = indexattributesBulkDeleteFailures;
            IndexattributesPrincipalObjectAttributeAccesses = indexattributesPrincipalObjectAttributeAccesses;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "recordid")]
        public long? Recordid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "versionnumber")]
        public string Versionnumber { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexid")]
        public string Indexid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributeid")]
        public string Indexattributeid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributes_SyncErrors")]
        public IList<MicrosoftDynamicsCRMsyncerror> IndexattributesSyncErrors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributes_AsyncOperations")]
        public IList<MicrosoftDynamicsCRMasyncoperation> IndexattributesAsyncOperations { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributes_MailboxTrackingFolders")]
        public IList<MicrosoftDynamicsCRMmailboxtrackingfolder> IndexattributesMailboxTrackingFolders { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributes_BulkDeleteFailures")]
        public IList<MicrosoftDynamicsCRMbulkdeletefailure> IndexattributesBulkDeleteFailures { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "indexattributes_PrincipalObjectAttributeAccesses")]
        public IList<MicrosoftDynamicsCRMprincipalobjectattributeaccess> IndexattributesPrincipalObjectAttributeAccesses { get; set; }

    }
}
