// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CRM.Interface.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Collection of rra_question
    /// </summary>
    /// <remarks>
    /// Microsoft.Dynamics.CRM.rra_questionCollection
    /// </remarks>
    public partial class MicrosoftDynamicsCRMrraQuestionCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrraQuestionCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMrraQuestionCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// MicrosoftDynamicsCRMrraQuestionCollection class.
        /// </summary>
        public MicrosoftDynamicsCRMrraQuestionCollection(IList<MicrosoftDynamicsCRMrraQuestion> value = default(IList<MicrosoftDynamicsCRMrraQuestion>))
        {
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public IList<MicrosoftDynamicsCRMrraQuestion> Value { get; set; }

    }
}
